import { Syne, Urbanist } from 'next/font/google';
import Header from './ui/header/header';
import Footer from './ui/footer/footer';
import AuthProvider from '../providers/SessionProvider';
import '../globals.scss';

const SyneSans = Syne({
  variable: '--font-syne-sans',
  subsets: ['latin'],
});
const UrbanistSans = Urbanist({
  variable: '--font-urbanist-sans',
  subsets: ['latin'],
});

export const metadata = {
  title: 'BlogHive',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${SyneSans.variable} ${UrbanistSans.variable} layout`}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
