import { Syne, Urbanist } from 'next/font/google';
import { ToastContainer, toast } from 'react-toastify';
import './globals.scss';

const SyneSans = Syne({
  variable: '--font-syne-sans',
  subsets: ['latin'],
});
const UrbanistSans = Urbanist({
  variable: '--font-urbanist-sans',
  subsets: ['latin'],
});

export const metadata = {
  title: 'BlogHive',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <ToastContainer />
      {children}
    </>
  );
}
